In [5]:
import pandas as pd

In [7]:
df = pd.read_csv("shirts.csv")

In [8]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,18719236,SPYKAR,Men Blue Slim Fit Faded Casual Shirt,2.9,12,2999.0,50.0,"""₹1,499.00""",INR,http://assets.myntassets.com/assets/images/187...,...,"{""1_star"":6,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",SPY███ LI███TYL█████████E L█████████,"[{""size"":""38"",""value"":""38.0in"",""value_name"":""C...",NaN,19t███loo███F W█████████s C███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
1,18960048,The Indian Garage Co,Men White & Beige Striped Casual Shirt,4.2,128,1749.0,74.0,"""₹507.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":8,""2_stars"":3,""3_stars"":14,""4_stars""...","[{""percentage"":""63"",""value_name"":""Fit, Just Ri...",Tru███t C███erc███,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...",NaN,1 s███loo███Cab█████████-01███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
2,18960188,The Indian Garage Co,Men White & Charcoal Grey Printed Cotton Casua...,4.4,35,1749.0,74.0,"""₹454.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",THE███DIA███ARA█████████,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...",NaN,2/1███rve███o.4█████████hal███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
3,18960016,The Indian Garage Co,Men Cream-Coloured Solid Casual Shirt,4.0,102,1749.0,74.0,"""₹454.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":8,""2_stars"":9,""3_stars"":11,""4_stars""...","[{""percentage"":""75"",""value_name"":""Fit, Just Ri...",THE███DIA███ARA█████████,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...",NaN,2/1███rve███o.4█████████hal███████████████████...,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
4,18996778,U.S. Polo Assn.,U S Polo Assn Men Blue Gingham Checks Patch Po...,4.2,10,2599.0,50.0,"""₹1,559.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""38"",""value"":""39.5in"",""value_name"":""C...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts

In [9]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
92,20308620,Arrow,Men Blue Original Slim Fit Grid Tattersall Che...,4.0,59,2499.0,50.0,"""₹2,499.00""",INR,http://assets.myntassets.com/assets/images/203...,...,"{""1_star"":6,""2_stars"":1,""3_stars"":11,""4_stars""...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",NaN,"[{""size"":""38"",""value"":""41.73in"",""value_name"":""...",NaN,NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",shirts
93,18960194,The Indian Garage Co,Men White Printed Casual Cotton Shirt,3.9,73,1749.0,72.0,"""₹349.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":8,""2_stars"":4,""3_stars"":11,""4_stars""...","[{""percentage"":""83"",""value_name"":""Fit, Just Ri...",THE███DIA███ARA█████████,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...",NaN,2/1███rve███o.4█████████hal███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 449 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
94,19276504,Turtle,Men Beige Printed Cotton Slim Fit Casual Shirt,4.7,7,1399.0,40.0,"""₹839.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, A Littl...",Tur███ Li███ed,"[{""size"":""39"",""value"":""43.0in"",""value_name"":""C...",NaN,Lem███Fre███ Bl█████████d F███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
95,19299798,Louis Philippe,Men Navy Blue Solid Slim Fit Formal Shirt,4.4,32,2799.0,NaN,"""₹2,519.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Ret███Net███,"[{""size"":""39"",""value"":""44.15in"",""value_name"":""...",NaN,Blo███B-1███abi█████████-24███████████████████...,NaN,"{""applicable_on"":""Purchase of 3 or more items ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
96,18903374,Levis,Women Blue Pure Cotton Casual Shirt,4.6,168,2599.0,45.0,"""₹2,079.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":7,""2_stars"":2,""3_stars"":8,""4_stars"":...",NaN,Vis███ St███,"[{""size"":""XS"",""value"":""35.5in"",""value_name"":""B...",NaN,3rd███oor███o. █████████Mai███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts

In [10]:
df.shape

(97, 24)

In [11]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='str')

In [12]:
df.dtypes

product_id                  int64
title                         str
product_description           str
rating                    float64
ratings_count               int64
initial_price             float64
discount                  float64
final_price                   str
currency                      str
images                        str
delivery_options              str
product_details               str
breadcrumbs                   str
product_specifications        str
amount_of_stars               str
what_customers_said           str
seller_name                   str
sizes                         str
videos                        str
seller_information            str
variations                    str
best_offer                    str
more_offers                   str
category                      str
dtype: object

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              97 non-null     int64
 1   title                   97 non-null     str
 2   product_description     97 non-null     str
 3   rating                  97 non-null     float64
 4   ratings_count           97 non-null     int64
 5   initial_price           97 non-null     float64
 6   discount                87 non-null     float64
 7   final_price             97 non-null     str
 8   currency                97 non-null     str
 9   images                  97 non-null     str
 10  delivery_options        97 non-null     str
 11  product_details         97 non-null     str
 12  breadcrumbs             97 non-null     str
 13  product_specifications  97 non-null     str
 14  amount_of_stars         97 non-null     str
 15  what_customers_said     63 non-null     str
 16  seller_name             67 non-null     str
 17  sizes                   97 non-null     str
 18  videos                  10 non-null     str
 19  seller_information      67 non-null     str
 20  variations              27 non-null     str
 21  best_offer              97 non-null     str
 22  more_offers             97 non-null     str
 23  category                97 non-null     str
dtypes: float64(3), int64(2), str(19)
memory usage: 18.3 KB

In [14]:
df.isnull().sum()

product_id                 0
title                      0
product_description        0
rating                     0
ratings_count              0
initial_price              0
discount                  10
final_price                0
currency                   0
images                     0
delivery_options           0
product_details            0
breadcrumbs                0
product_specifications     0
amount_of_stars            0
what_customers_said       34
seller_name               30
sizes                      0
videos                    87
seller_information        30
variations                70
best_offer                 0
more_offers                0
category                   0
dtype: int64

In [23]:
df = pd.read_csv("shirts.csv")

In [25]:
df["discount"] = df["discount"].fillna(df["discount"].mean())

In [27]:
df["seller_name"] = df["seller_name"].fillna("Unknown")

In [28]:
df.isnull().sum()

product_id                 0
title                      0
product_description        0
rating                     0
ratings_count              0
initial_price              0
discount                   0
final_price                0
currency                   0
images                     0
delivery_options           0
product_details            0
breadcrumbs                0
product_specifications     0
amount_of_stars            0
what_customers_said       34
seller_name                0
sizes                      0
videos                    87
seller_information        30
variations                70
best_offer                 0
more_offers                0
category                   0
dtype: int64

In [30]:
df[["discount","sizes"]]

     discount                                              sizes
0   50.000000  [{"size":"38","value":"38.0in","value_name":"C...
1   74.000000  [{"size":"38","value":"38.5in","value_name":"C...
2   74.000000  [{"size":"38","value":"38.5in","value_name":"C...
3   74.000000  [{"size":"38","value":"38.5in","value_name":"C...
4   50.000000  [{"size":"38","value":"39.5in","value_name":"C...
..        ...                                                ...
92  50.000000  [{"size":"38","value":"41.73in","value_name":"...
93  72.000000  [{"size":"38","value":"38.5in","value_name":"C...
94  40.000000  [{"size":"39","value":"43.0in","value_name":"C...
95  55.873563  [{"size":"39","value":"44.15in","value_name":"...
96  45.000000  [{"size":"XS","value":"35.5in","value_name":"B...

[97 rows x 2 columns]

In [32]:
filtered_data = df[df["discount"] > 60.0]
filtered_data.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
1,18960048,The Indian Garage Co,Men White & Beige Striped Casual Shirt,4.2,128,1749.0,74.0,"""₹507.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":8,""2_stars"":3,""3_stars"":14,""4_stars""...","[{""percentage"":""63"",""value_name"":""Fit, Just Ri...",Tru███t C███erc███,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...",NaN,1 s███loo███Cab█████████-01███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
2,18960188,The Indian Garage Co,Men White & Charcoal Grey Printed Cotton Casua...,4.4,35,1749.0,74.0,"""₹454.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, A Litt...",THE███DIA███ARA█████████,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...",NaN,2/1███rve███o.4█████████hal███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
3,18960016,The Indian Garage Co,Men Cream-Coloured Solid Casual Shirt,4.0,102,1749.0,74.0,"""₹454.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":8,""2_stars"":9,""3_stars"":11,""4_stars""...","[{""percentage"":""75"",""value_name"":""Fit, Just Ri...",THE███DIA███ARA█████████,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...",NaN,2/1███rve███o.4█████████hal███████████████████...,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
7,18960086,The Indian Garage Co,Men Green Slim Fit Horizontal Stripes Casual S...,4.5,23,1749.0,72.0,"""₹454.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":2,""4_stars"":...","[{""percentage"":""75"",""value_name"":""Fit, Just Ri...",THE███DIA███ARA█████████Y -██████,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...",NaN,"No.███1, ███ur █████████lur█████████████████████8","[{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts
8,18960098,The Indian Garage Co,Men Black & White Printed Casual Cotton Shirt,3.8,5,1749.0,76.0,"""₹419.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":0,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Tru███t C███erc███,"[{""size"":""38"",""value"":""38.74in"",""value_name"":""...",NaN,1 s███loo███Cab█████████-01███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 449 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts

df.duplicated().sum()

In [34]:
df = df.drop_duplicates()

In [35]:
df["price_category"] = df["initial_price"].apply(lambda x: "Expensive" if x > 2000.0 else "Affordable")

In [36]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,price_category
0,18719236,SPYKAR,Men Blue Slim Fit Faded Casual Shirt,2.9,12,2999.0,50.0,"""₹1,499.00""",INR,http://assets.myntassets.com/assets/images/187...,...,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",SPY███ LI███TYL█████████E L█████████,"[{""size"":""38"",""value"":""38.0in"",""value_name"":""C...",NaN,19t███loo███F W█████████s C███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts,Expensive
1,18960048,The Indian Garage Co,Men White & Beige Striped Casual Shirt,4.2,128,1749.0,74.0,"""₹507.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"[{""percentage"":""63"",""value_name"":""Fit, Just Ri...",Tru███t C███erc███,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...",NaN,1 s███loo███Cab█████████-01███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts,Affordable
2,18960188,The Indian Garage Co,Men White & Charcoal Grey Printed Cotton Casua...,4.4,35,1749.0,74.0,"""₹454.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"[{""percentage"":""100"",""value_name"":""Fit, A Litt...",THE███DIA███ARA█████████,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...",NaN,2/1███rve███o.4█████████hal███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts,Affordable
3,18960016,The Indian Garage Co,Men Cream-Coloured Solid Casual Shirt,4.0,102,1749.0,74.0,"""₹454.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"[{""percentage"":""75"",""value_name"":""Fit, Just Ri...",THE███DIA███ARA█████████,"[{""size"":""38"",""value"":""38.5in"",""value_name"":""C...",NaN,2/1███rve███o.4█████████hal███████████████████...,"[{},{},{},{},{},{}]","{""applicable_on"":""Orders above Rs. 649 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts,Affordable
4,18996778,U.S. Polo Assn.,U S Polo Assn Men Blue Gingham Checks Patch Po...,4.2,10,2599.0,50.0,"""₹1,559.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""38"",""value"":""39.5in"",""value_name"":""C...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",shirts,Expensive

In [37]:
df.to_csv("cleaned_shopping_data.csv", index=False)

Summary:

1. Loaded shopping dataset using Pandas.
2. Explored dataset structure and data types.
3. Identified and handled missing values.
4. Performed filtering and column selection.
5. Removed duplicate rows.
6. Created a new column: price_category.
7. Saved cleaned dataset into a new CSV file.